version: '3'
services:
  web:
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./:/app
    networks:
      - backend
    links:
      - redis
  redis:
    image: redis:5-alpine
    ports:
      - 16379:6379
networks:
  backend:
    driver: bridge